name: Deploy Zappa on main

on:
  push:
    branches:
      - main
      - git-actions-backend

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Part2/Part2_Backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('Part2/Part2_Backend/requirements.txt') }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Inject environment variables into zappa_settings.json
        run: |
          jq --arg env "${{ vars.ENV }}" \
             --arg s3_key "${{ secrets.S3_AWS_ACCESS_KEY_ID }}" \
             --arg s3_secret "${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}" \
             --arg s3_region "${{ secrets.S3_AWS_REGION }}" \
             --arg db_url "${{ secrets.DATABASE_URL }}" \
             --ARG s3_bucket "${{ secrets.S3_BUCKET_NAME }}" \
             '.dev.environment_variables.ENV = $env |
              .dev.environment_variables.S3_AWS_ACCESS_KEY_ID = $s3_key |
              .dev.environment_variables.S3_AWS_SECRET_ACCESS_KEY = $s3_secret |
              .dev.environment_variables.S3_AWS_REGION = $s3_region |
              .dev.environment_variables.DATABASE_URL = $db_url' |
              .dev.environment_variables.S3_BUCKET_NAME = $s3_bucket \
             zappa_settings.json > tmp && mv tmp zappa_settings.json

      - name: Create virtualenv, install packages, and deploy with Zappa
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade zappa
          if zappa status -s zappa_settings.json dev >/dev/null 2>&1; then
            zappa update -s zappa_settings.json dev
          else
            zappa deploy -s zappa_settings.json dev
          fi